package uk.ac.ed.bikerental;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;

/**
 * This class handles searching for quotes from the bike providers, taking in the search criteria needed for this
 */
public class Search {
	private Location location;
	private DateRange dates;
	private Map<BikeType, Integer> bikes;
	public ArrayList<BikeProvider> providers;

	/**Constructor takes in the search critera passed in by the user
	 *
	 * @param location the location to search near
	 * @param dates the dates the bikes should be rented for
	 * @param bikes a map of bike type to quantity desired
	 * @param providers a collection of BikeProviders to get quotes from
	 */
	public Search(Location location, DateRange dates, Map<BikeType, Integer> bikes, ArrayList<BikeProvider> providers) {
		this.location = location;
		this.dates = dates;
		this.bikes = bikes;
		this.providers = providers;
	}

	/**
	 * This will loop through the BikeProviders, check that they are near the location criterion and if so
	 * generate a quote from said provider
	 *
	 * @return  a collection of quotes generated by the bike providers
	 */
	public Collection<Quote> getQuotes(){

		ArrayList<Quote> quotes = new ArrayList<Quote>();
		for (BikeProvider bp : providers) {
			if (location.isNearTo(bp.getLocation())) {
				Quote generatedQuote = bp.generateQuote(bikes, dates);
				if (generatedQuote != null) quotes.add(generatedQuote);
			}
		}
		return quotes;
	}
	
	
}
